Fix type
joshuaLattke/prrueba-de-platzi-1 pull request #1
Opened 2022-04-08 21:31 UTC by joshuaLattke

2022-04-08 21:32 UTC, joshuaLattke commented
prueba de pull request

2022-04-08 22:29 UTC, danielnxnx requested changes
usar entidades de HTML

2022-04-11 17:00 UTC, joshuaLattke commented
cambios realizados

2022-04-11 17:10 UTC, danielnxnx approved these changes
cambios aprobados

2022-04-11 17:12 UTC, merged